export const BOOK_STATUSES = ['TO_READ', 'READING', 'READ', 'PAUSED', 'ABANDONED'];
export const MOOD_TAGS = ['MOVED', 'CALM', 'JOYFUL', 'SAD', 'ANGRY', 'CONFUSED', 'RELIEVED', 'EMPTY', 'CHANGED'];
export const TRACE_TYPES = ['DOG_EAR', 'ANNOTATION', 'REREAD_MARK'];
export const EXCERPT_CARD_STATUSES = ['ACTIVE', 'DEGRADED'];
export const EXCERPT_SOURCE_STATES = ['LINKED', 'DEGRADED'];
export const ACTIVITY_ACTIONS = ['CREATED', 'UPDATED', 'DELETED', 'RESTORED', 'STATUS_CHANGED', 'COMPLETED'];
export const ACTIVITY_ENTITY_TYPES = [
  'BOOK',
  'DOG_EAR',
  'ANNOTATION',
  'REREAD_MARK',
  'COMPLETION_REFLECTION',
  'EXCERPT_CARD',
  'EXCERPT_SOURCE'
];
